### ISSUE TITLE
Collect feedback on architectural diagram for ETL

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/cancer-data-aggregator#2]
Call for feedback on CDA's current architectural diagram for ETL and review again during our next call on 8-Oct.

**Comment by anniekuan** [comment]
Architectural diagram can be found in the [CDA Q4 Technical Project Plan](https://docs.google.com/document/d/1LE6VPn09eTZUWgst8Gj5zWBm1zuvbcfuvdBmuvw4pNM/edit#heading=h.mutjwx5sxta0).
